### ISSUE TITLE
Ketos Login Screen Unresponsive

### ISSUE THREAD

**Issue by jessiemongeon** [juliangruendner/ketos_develop#1]
Hi, I've recently installed ketos on an ec2 instance and it looks like everything is up and running correctly, but when I access the /login screen and input credentials, the login button is unresponsive and does nothing. There is no error message or feedback from the button. 

Does this have to do with launching the ketos_gui app? 
When trying to launch this app with npm install and npm start such as the README details, the install fails because it cannot install the fsevents module since I am running on an ec2 linux instance. Is this meant to be built on MacOSX for this module? It seems like the app does not start unless you have this module, which I cannot get.

**Comment by juliangruendner** [comment]
there was an issue with one of the libraries used in the the brain api, which the GUI connects to.
I have fixed this and checked in a new install package - see: https://github.com/juliangruendner/ketos_develop/blob/master/build_from_images/ketos_v0.2.1.zip

I have never tried to run the app in dev mode on linux before. However I have started the GUI app in develop mode on mac as well as windows. As it works fine on windows i dont think the fsevents should be an issue.
